version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_vols:/data/db
  
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo

volumes:
  mongo_vols: {}