version: '3.9'

services:  
  api:
    build: .
    ports:
      - 80:8080
    environment:
      - ACCESS_SECRET_ID=$ACCESS_SECRET_ID
      - ACCESS_KEY_ID=$ACCESS_KEY_ID
      - AWS_BUCKET=$AWS_BUCKET
      - AWS_TABLE=$AWS_TABLE
      - AWS_REGION=$AWS_REGION