version: '3.9'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_vols:/data/db
  
  api:
    build: .
    ports:
      - 80:8080
    depends_on:
      - mongo
    environment:
      - ACCESS_SECRET_ID=$ACCESS_SECRET_ID
      - ACCESS_KEY_ID=$ACCESS_KEY_ID
      - AWS_BUCKET=$AWS_BUCKET

volumes:
  mongo_vols: {}