apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filetransfer
  name: filetransfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filetransfer
  template:
    metadata:
      labels:
        app: filetransfer
    spec:
      containers:
      - image: danielbeh/filetransfer-cl
        name: filetransfer
        env:
        - name: ACCESS_SECRET_ID
          value: <YOUR_ACCESS_ID>
        - name: ACCESS_KEY_ID
          value: <YOUR_ACCESS_KEY>
        - name: AWS_BUCKET
          value: <YOUR_BUCKET>
        - name: AWS_TABLE
          value: <YOUR_TABLE>
        - name: AWS_REGION
          value: <YOUR_REGION>
        ports:
        - containerPort: 80
          name: filetransfer