apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filetransfer
  name: filetransfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filetransfer
  template:
    metadata:
      labels:
        app: filetransfer
    spec:
      containers:
      - image: danielbeh/filetransfer-cl
        name: filetransfer
        env:
        - name: ACCESS_SECRET_ID
          value: UosgVA4GKfFdi91ik7Tx3cQy+5oSAclAvKp3/tes
        - name: ACCESS_KEY_ID
          value: AKIAX3GQE7IN5VP36OPL
        - name: AWS_BUCKET
          value: danielbehar
        - name: AWS_TABLE
          value: FileTrans
        - name: AWS_REGION
          value: us-east-1
        ports:
        - containerPort: 80
          name: filetransfer