apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filetransfer
  name: filetransfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filetransfer
  template:
    metadata:
      labels:
        app: filetransfer
    spec:
      containers:
      - image: danielbeh/filetransfer-cl
        name: filetransfer
        env:
        - name: ACCESS_SECRET_ID
          value: ooPot2GDyqtIaArCd5zCSAtC+QP7P3qtYU/O6DrK
        - name: ACCESS_KEY_ID
          value: AKIAX3GQE7INUDRHJ3EF
        - name: AWS_BUCKET
          value: filetransbuck
        - name: AWS_TABLE
          value: TransFile
        - name: AWS_REGION
          value: us-east-1
        ports:
        - containerPort: 80
          name: filetransfer