apiVersion: v1
kind: Service
metadata:
  labels:
    app: filetransfer
  name: filetransfer
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: filetransfer
  